version: '3.3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'gradesdb'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
  test-db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'gradesdbtest'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3307:3306'
    expose:
      - '3307'
      # Where our data will be persisted
    volumes:
      - test-db:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
# Names our volume
volumes:
  db:
  test-db: